-- The SQLite schema in Database.Schema, as it stands once Database.Migrate has run,
-- translated to PostgreSQL. Differences worth knowing about:
--
-- * Timestamps are timestamptz rather than sortable text. The repositories format
--   them back to SQLite's "yyyy-MM-dd HH:mm:ss" on the way out, so the API does not
--   change.
-- * COLLATE NOCASE becomes citext, which is what makes "Alice" and "alice" the same
--   username and the same address here as they are there.
-- * Card ids, sets and the other facet columns are COLLATE "C": byte order, as in
--   SQLite. A locale collation ignores punctuation and would sort OP01-016_p1
--   somewhere other than straight after OP01-016.
-- * Identity columns start at 1 the same as AUTOINCREMENT, which matters: account 1
--   is the owner.

CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE catalog (
    card_id   TEXT COLLATE "C" PRIMARY KEY,
    base_id   TEXT COLLATE "C" NOT NULL,
    variant   TEXT COLLATE "C" NOT NULL DEFAULT '',
    name      TEXT NOT NULL,
    set_label TEXT COLLATE "C",
    set_name  TEXT,
    rarity    TEXT COLLATE "C",
    category  TEXT COLLATE "C",
    colors    TEXT COLLATE "C",
    cost      INTEGER,
    power     INTEGER,
    counter   INTEGER,
    types     TEXT,
    effect    TEXT,
    image_url TEXT
);
CREATE INDEX idx_catalog_base ON catalog (base_id);
CREATE INDEX idx_catalog_set  ON catalog (set_label);
-- Search is a substring match on name and type, which no btree can serve.
CREATE INDEX idx_catalog_name_trgm  ON catalog USING gin (name gin_trgm_ops);
CREATE INDEX idx_catalog_types_trgm ON catalog USING gin (types gin_trgm_ops);

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      CITEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    email         CITEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen     TIMESTAMPTZ
);
-- Partial for the same reason as in SQLite: accounts from before the column all
-- have none, and they must not collide with each other.
CREATE UNIQUE INDEX idx_users_email ON users (email) WHERE email IS NOT NULL;

CREATE TABLE access_requests (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email             CITEXT NOT NULL,
    note              TEXT NOT NULL DEFAULT '',
    status            TEXT NOT NULL DEFAULT 'pending',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    decided_at        TIMESTAMPTZ,
    decided_by        TEXT,
    requested_from    TEXT,
    action_token_hash TEXT UNIQUE,
    action_expires_at TIMESTAMPTZ,
    invite_token_hash TEXT UNIQUE,
    invite_expires_at TIMESTAMPTZ,
    invite_sent_at    TIMESTAMPTZ,
    used_at           TIMESTAMPTZ,
    user_id           BIGINT
);
CREATE INDEX idx_access_status ON access_requests (status, id DESC);
CREATE INDEX idx_access_email  ON access_requests (email, id DESC);

CREATE TABLE sessions (
    token_hash TEXT PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen  TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_sessions_user    ON sessions (user_id);
CREATE INDEX idx_sessions_expires ON sessions (expires_at);

-- No foreign key to users, as in SQLite: rows from before accounts existed belong
-- to user 0 until the first account claims them.
CREATE TABLE collection (
    user_id    BIGINT NOT NULL,
    card_id    TEXT COLLATE "C" NOT NULL,
    qty        INTEGER NOT NULL CHECK (qty >= 0),
    note       TEXT NOT NULL DEFAULT '',
    added_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, card_id)
);
CREATE INDEX idx_collection_user_updated ON collection (user_id, updated_at DESC);

CREATE TABLE scan_log (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL DEFAULT 0,
    card_id TEXT,
    result  TEXT,
    at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_scan_log_user ON scan_log (user_id);

CREATE TABLE prices (
    card_id    TEXT COLLATE "C" PRIMARY KEY,
    usd        DOUBLE PRECISION,
    gbp        DOUBLE PRECISION,
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE decks (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT NOT NULL DEFAULT 0,
    name           TEXT NOT NULL,
    leader_card_id TEXT COLLATE "C" NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_decks_user_updated ON decks (user_id, updated_at DESC);

CREATE TABLE deck_cards (
    deck_id BIGINT NOT NULL REFERENCES decks (id) ON DELETE CASCADE,
    card_id TEXT COLLATE "C" NOT NULL,
    qty     INTEGER NOT NULL CHECK (qty > 0),
    PRIMARY KEY (deck_id, card_id)
);
