-- Background work and card art. Mirrors the jobs and card_images tables in
-- Database.Schema; see JobQueue for how a job row moves through its states.

CREATE TABLE jobs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type           TEXT NOT NULL,
    payload        TEXT NOT NULL DEFAULT '{}',
    status         TEXT NOT NULL DEFAULT 'queued',
    attempts       INTEGER NOT NULL DEFAULT 0,
    max_attempts   INTEGER NOT NULL DEFAULT 5,
    priority       INTEGER NOT NULL DEFAULT 0,
    run_after      TIMESTAMPTZ NOT NULL DEFAULT now(),
    locked_until   TIMESTAMPTZ,
    dedupe_key     TEXT,
    correlation_id TEXT,
    user_id        BIGINT,
    result         TEXT,
    last_error     TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- At most one live job per dedupe key: asking twice for the same picture, or
-- two containers scheduling the same purge, queues it once.
CREATE UNIQUE INDEX idx_jobs_dedupe ON jobs (dedupe_key)
    WHERE dedupe_key IS NOT NULL AND status IN ('queued', 'running');
CREATE INDEX idx_jobs_ready ON jobs (status, priority DESC, run_after);

CREATE TABLE card_images (
    card_id         TEXT COLLATE "C" PRIMARY KEY,
    status          TEXT NOT NULL DEFAULT 'pending',
    source_url      TEXT,
    object_key      TEXT,
    last_attempt_at TIMESTAMPTZ,
    next_attempt_at TIMESTAMPTZ,
    failure_count   INTEGER NOT NULL DEFAULT 0,
    last_error      TEXT,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
