-- Binders: a collection belongs to a binder rather than straight to an account.
-- Every account has one personal binder ("Mine"); shared binders have several
-- members, each of whom can read and change it. Mirrors Database.Schema.

CREATE TABLE binders (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL,
    kind       TEXT NOT NULL CHECK (kind IN ('personal', 'shared')),
    -- The account a personal binder belongs to; who made a shared one.
    owner_id   BIGINT,
    -- Personal binders only: whether people sharing a binder with the owner may
    -- look at it, read-only.
    visible    BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX idx_binders_personal ON binders (owner_id) WHERE kind = 'personal';

CREATE TABLE binder_members (
    binder_id BIGINT NOT NULL REFERENCES binders(id) ON DELETE CASCADE,
    user_id   BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    added_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (binder_id, user_id)
);
CREATE INDEX idx_binder_members_user ON binder_members (user_id);

-- Each existing account's personal binder takes the account's own id, so the
-- collection rows already keyed by that id need only their column renamed.
INSERT INTO binders (id, name, kind, owner_id)
    SELECT id, 'Mine', 'personal', id FROM users;
INSERT INTO binder_members (binder_id, user_id)
    SELECT id, id FROM users;
SELECT setval(pg_get_serial_sequence('binders', 'id'), COALESCE(MAX(id), 0) + 1, false)
    FROM binders;

-- Rows still at 0 predate accounts; the first account claims them, as before.
ALTER TABLE collection RENAME COLUMN user_id TO binder_id;
ALTER INDEX idx_collection_user_updated RENAME TO idx_collection_binder_updated;
-- Who first logged the card into this binder, shown in shared binders.
ALTER TABLE collection ADD COLUMN added_by BIGINT;
UPDATE collection SET added_by = binder_id WHERE binder_id <> 0;
